Update data_ingestion.yml

diff --git a/.github/workflows/data_ingestion.yml b/.github/workflows/data_ingestion.yml
--- a/.github/workflows/data_ingestion.yml
+++ b/.github/workflows/data_ingestion.yml
@@ -25,14 +25,22 @@ jobs:
       run: |
         cd Global_Crime_Data_Pipeline/scripts/
         python3 data_ingestion.py
-    
-       - name: Upload Crime Data
+    - name: Upload Crime Data
       run: |
-        mkdir -p Global_Crime_Data_Pipeline/data/raw
-        mv Global_Crime_Data_Pipeline/scripts/crime_data.csv Global_Crime_Data_Pipeline/data/raw/
-        cd Global_Crime_Data_Pipeline/data/raw/
-        git config --global user.email "shraddha_p09@hotmail.com"
-        git config --global user.name "shraddha0925"
-        git add crime_data.csv
-        git commit -m "Added crime_data.csv from GitHub Action"
-        git push
+        if [ -f Global_Crime_Data_Pipeline/scripts/crime_data.csv ]; then
+            mkdir -p Global_Crime_Data_Pipeline/data/raw
+            mv Global_Crime_Data_Pipeline/scripts/crime_data.csv Global_Crime_Data_Pipeline/data/raw/
+            cd Global_Crime_Data_Pipeline/data/raw/
+            git config --global user.email "shraddha_p09@hotmail.com"
+            git config --global user.name "shraddha0925"
+            git add crime_data.csv
+            git commit -m "Added crime_data.csv from GitHub Action"
+            git push
+        else
+            echo "File not found: Global_Crime_Data_Pipeline/scripts/crime_data.csv"
+            exit 1
+        fi
+
+
+    
+      
